# Pipeline variables: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
stages:
  - frontend-stage
  - backend-stage

variables:
  DOCKER_IMAGE_NAME_TDV: "tdv-app"

build-frontend:
  image: node
  stage: frontend-stage
  script:
    - echo $CI_COMMIT_BRANCH
    - cd frontend/
    - npm install
    - npm run test -- --watchAll=false
    - npm run build
  artifacts:
    paths:
      - "frontend/build/"

build-backend:
  image: docker:latest
  stage: backend-stage
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      docker build --pull -t "$CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME_TDV" .
      docker push "$CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME_TDV"
  