stages:
  - build
  - deploy

build-frontend:
  image: node
  stage: build
  script:
    - pwd
    - cd frontend/
    - npm install
    - npm run test -- --watchAll=false
    - npm run build
  artifacts:
    paths:
      - "frontend/build/"

build-backend:
  extends: build-frontend
  image: node
  stage: build
  script:
    - pwd
    - ls -la build/
    - ls -la frontend/build/
    - cd backend/
    - ls -la ../frontend/build/
    - ls -la frontend/build/
  