stages:
  - frontend-stage
  - backend-stage
  - deploy

build-frontend:
  image: node
  stage: frontend-stage
  script:
    - pwd
    - cd frontend/
    - npm install
    - npm run test -- --watchAll=false
    - npm run build
  artifacts:
    paths:
      - "frontend/build/"

build-backend:
  image: node
  stage: backend-stage
  script:
    - pwd
    - ls -la build/
    - ls -la frontend/build/
    - cd backend/
    - ls -la ../frontend/build/
    - ls -la frontend/build/
  