# Pipeline variables: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
stages:
  - frontend-stage
  - backend-stage
  - deploy

build-frontend:
  image: node
  stage: frontend-stage
  script:
    - echo $CI_COMMIT_BRANCH
    - cd frontend/
    - npm install
    - npm run test -- --watchAll=false
    - npm run build
  artifacts:
    paths:
      - "frontend/build/"

build-backend:
  image: node
  stage: backend-stage
  script:
    - pwd
    - ls -la $CI_PROJECT_DIR/frontend/build/
    - cd backend/
    - ls -la $CI_PROJECT_DIR/frontend/build/
  