version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    restart: always
    networks:
      - publicnet
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--log.level=DEBUG"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  tdv-backend:
    image: registry.gitlab.ost.ch:45023/seproj/2024-fs/g14-traindelayvisualizer/traindelayvisualizer/tdv-app:v0.0.2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-router.rule=Host(`srbsci-112.ost.ch`)"
      - "traefik.http.routers.web-router.entrypoints=web"
      - "traefik.http.services.cldinf-web.loadbalancer.server.port=4000"
    restart: always
    networks:
      - publicnet
      - privatenet
    environment:
      - USE_ENV_VARIABLE=true
      - DATABASE_URL=postgres://pgUser:pgPassword@tdv-db:5432/tdv
      - SBB_API_ACTUAL_DATA_PREVIOUS_DAY=https://data.sbb.ch/api/explore/v2.1/catalog/datasets/actual-data-sbb-previous-day/exports/json?lang=de&timezone=Europe%2FBerlin

  db:
    image: postgres:16.1
    restart: always
    networks:
      - privatenet
    hostname: tdv-db
    environment:
      POSTGRES_DB: tdv
      POSTGRES_USER: pgUser
      POSTGRES_PASSWORD: pgPassword
    volumes:
      - postgres-database-volume:/var/lib/postgresql/data

networks:
  publicnet:
    driver: bridge
  privatenet:
    internal: true
    driver: bridge

volumes:
  postgres-database-volume:
    driver: local
