version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    restart: always
    networks:
      - tdv-network
    ports:
      - "80:80"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--providers.docker.network=tdv-network"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  tdv-backend:
    image: registry.gitlab.ost.ch:45023/seproj/2024-fs/g14-traindelayvisualizer/traindelayvisualizer/tdv-app:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-router.rule=Host(`srbsci-112.ost.ch`)"
      - "traefik.http.routers.web-router.entrypoints=web"
      - "traefik.http.services.tdv-backend.loadbalancer.server.port=4000"
    restart: always
    networks:
      - tdv-network
    environment:
      - USE_ENV_VARIABLE=true
      - NODE_ENV=production
      - DATABASE_URL=postgres://pgUser:pgPassword@tdv-db:5432/tdv
      - SBB_API_ACTUAL_DATA_PREVIOUS_DAY=https://opentransportdata.swiss/de/dataset/istdaten/permalink
      - SBB_API_TRAIN_STATION_DATA=https://opentransportdata.swiss/de/dataset/service-points-actual-date/permalink
    volumes:
      - tdv-backend-logs-v:/app/backend/data

  db:
    image: postgres:16.1
    restart: always
    networks:
      - tdv-network
    hostname: tdv-db
    environment:
      POSTGRES_DB: tdv
      POSTGRES_USER: pgUser
      POSTGRES_PASSWORD: pgPassword
    volumes:
      - postgres-database-v:/var/lib/postgresql/data

networks:
  tdv-network:
    driver: bridge

volumes:
  postgres-database-v:
    driver: local
  tdv-backend-logs-v:
    driver: local